### PR TITLE
Add automatic lint tests and fix all existing lints

### PR DESCRIPTION
**Pull request by jimhester**

### CODE REVIEW

**Comment by robertzk** [comment]
Nice! Will I have to update my PRs accordingly? I think I broke some conventions.

**Comment by jimhester** [comment]
I should be able to get travis to re-run your pull requests once this is merged and it then lintr should automatically comment on the pull requests if it finds an issue.

**Comment by jimhester** [comment]
Just want to make sure this passes everything (It does on my machine) before I merge it.

**Comment by robertzk** [comment]
Great; thanks!

**Comment by jimhester** [comment]
Looks like just restarting the builds won't work.  I will merge your pulls manually and fix any linting discrepancies locally, so no worries.

Thanks for all of the cleanup by the way, it is very helpful!

**Pull request merged**
